AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: This template is partially managed by Amazon.Lambda.Annotations (v1.0.0.0).
Parameters:
  DbConnectionStringParam:
    Type: String
    Default: Server=my-sqlserver,1433;Database=MyECommerceApp;User ID=sa;Password=Sqlserver123$;MultipleActiveResultSets=true;TrustServerCertificate=True;
Globals:
  Function:
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: myecommerceapp
        POWERTOOLS_LOG_LEVEL: Debug
        POWERTOOLS_LOGGER_CASE: CamelCase
        POWERTOOLS_METRICS_NAMESPACE: myecommerceapp
        POWERTOOLS_LOGGER_LOG_EVENT: true
        DbConnectionString:
          Ref: DbConnectionStringParam
        TopicArn:
          Ref: SNSTopic
Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "myecommercetopic"
  MyECommerceAppClientRequestsApproveClientRequestHandleGenerated:
    Type: AWS::Serverless::Function
    Metadata:
      Tool: Amazon.Lambda.Annotations
      SyncedEvents:
        - RootPost
    Properties:
      Runtime: dotnet6
      CodeUri: .
      MemorySize: 256
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - SNSPublishMessagePolicy:
            TopicName:
              Ref: SNSTopic
      PackageType: Zip
      Handler: MyECommerceApp::MyECommerceApp.ClientRequests.ApproveClientRequest_Handle_Generated::Handle
      Events:
        RootPost:
          Type: Api
          Properties:
            Path: /client-requests/{clientRequestId}/approve
            Method: POST
  MyECommerceAppClientRequestsRegisterClientRequestHandleGenerated:
    Type: AWS::Serverless::Function
    Metadata:
      Tool: Amazon.Lambda.Annotations
      SyncedEvents:
        - RootPost
    Properties:
      Runtime: dotnet6
      CodeUri: .
      MemorySize: 256
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
      PackageType: Zip
      Handler: MyECommerceApp::MyECommerceApp.ClientRequests.RegisterClientRequest_Handle_Generated::Handle
      Events:
        RootPost:
          Type: Api
          Properties:
            Path: /client-requests
            Method: POST
  MyECommerceAppClientsRegisterClientHandleGenerated:
    Type: AWS::Serverless::Function
    Metadata:
      Tool: Amazon.Lambda.Annotations
    Properties:
      Runtime: dotnet6
      CodeUri: .
      MemorySize: 256
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
      PackageType: Zip
      Handler: MyECommerceApp::MyECommerceApp.Clients.RegisterClient_Handle_Generated::Handle
      Events:
        RootEvent:
          Type: SNS
          Properties:
            Topic:
              Ref: SNSTopic
            FilterPolicy:
              event:
                - clientrequestapproved
            SqsSubscription: true
  MyECommerceAppClientsGetClientsHandleGenerated:
    Type: AWS::Serverless::Function
    Metadata:
      Tool: Amazon.Lambda.Annotations
      SyncedEvents:
        - RootGet
    Properties:
      Runtime: dotnet6
      CodeUri: .
      MemorySize: 256
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
      PackageType: Zip
      Handler: MyECommerceApp::MyECommerceApp.Clients.GetClients_Handle_Generated::Handle
      Events:
        RootGet:
          Type: Api
          Properties:
            Path: /clients/{clientId}
            Method: GET
  MyECommerceAppProductsRegisterProductHandleGenerated:
    Type: AWS::Serverless::Function
    Metadata:
      Tool: Amazon.Lambda.Annotations
      SyncedEvents:
        - RootPost
    Properties:
      Runtime: dotnet6
      CodeUri: .
      MemorySize: 256
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
      PackageType: Zip
      Handler: MyECommerceApp::MyECommerceApp.Products.RegisterProduct_Handle_Generated::Handle
      Events:
        RootPost:
          Type: Api
          Properties:
            Path: /products
            Method: POST
  MyECommerceAppProductsEnableProductHandleGenerated:
    Type: AWS::Serverless::Function
    Metadata:
      Tool: Amazon.Lambda.Annotations
      SyncedEvents:
        - RootPost
    Properties:
      Runtime: dotnet6
      CodeUri: .
      MemorySize: 256
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
      PackageType: Zip
      Handler: MyECommerceApp::MyECommerceApp.Products.EnableProduct_Handle_Generated::Handle
      Events:
        RootPost:
          Type: Api
          Properties:
            Path: /products/{productId}/enable
            Method: POST
  MyECommerceAppShoppingCartAddProductToShoppingCartHandleGenerated:
    Type: AWS::Serverless::Function
    Metadata:
      Tool: Amazon.Lambda.Annotations
      SyncedEvents:
        - RootPost
    Properties:
      Runtime: dotnet6
      CodeUri: .
      MemorySize: 256
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
      PackageType: Zip
      Handler: MyECommerceApp::MyECommerceApp.ShoppingCart.AddProductToShoppingCart_Handle_Generated::Handle
      Events:
        RootPost:
          Type: Api
          Properties:
            Path: /shopping-cart
            Method: POST
  MyECommerceAppShoppingCartCleanShoppingCartHandleGenerated:
    Type: AWS::Serverless::Function
    Metadata:
      Tool: Amazon.Lambda.Annotations
    Properties:
      Runtime: dotnet6
      CodeUri: .
      MemorySize: 256
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
      PackageType: Zip
      Handler: MyECommerceApp::MyECommerceApp.ShoppingCart.CleanShoppingCart_Handle_Generated::Handle
      Events:
        RootEvent:
          Type: SNS
          Properties:
            Topic:
              Ref: SNSTopic
            FilterPolicy:
              event:
                - orderregistered
            SqsSubscription: true
  MyECommerceAppOrdersPlaceOrderHandleGenerated:
    Type: AWS::Serverless::Function
    Metadata:
      Tool: Amazon.Lambda.Annotations
      SyncedEvents:
        - RootPost
    Properties:
      Runtime: dotnet6
      CodeUri: .
      MemorySize: 256
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - SNSPublishMessagePolicy:
            TopicName:
              Ref: SNSTopic
      PackageType: Zip
      Handler: MyECommerceApp::MyECommerceApp.Orders.PlaceOrder_Handle_Generated::Handle
      Events:
        RootPost:
          Type: Api
          Properties:
            Path: /orders
            Method: POST
  MyECommerceAppClientRequestsListClientRequestsHandleGenerated:
    Type: AWS::Serverless::Function
    Metadata:
      Tool: Amazon.Lambda.Annotations
      SyncedEvents:
        - RootGet
    Properties:
      Runtime: dotnet6
      CodeUri: .
      MemorySize: 256
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
      PackageType: Zip
      Handler: MyECommerceApp::MyECommerceApp.ClientRequests.ListClientRequests_Handle_Generated::Handle
      Events:
        RootGet:
          Type: Api
          Properties:
            Path: /client-requests
            Method: GET
